export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  DAYHOME_NOT_FOUND: 'DAYHOME_NOT_FOUND',
  DAYHOME_ALREADY_ACTIVE: 'DAYHOME_ALREADY_ACTIVE',
  DAYHOME_SUSPENDED: 'DAYHOME_SUSPENDED',
  CHILD_NOT_FOUND: 'CHILD_NOT_FOUND',
  CHILD_ALREADY_ENROLLED: 'CHILD_ALREADY_ENROLLED',
  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  EDUCATOR_NOT_FOUND: 'EDUCATOR_NOT_FOUND',
  ROOM_AT_CAPACITY: 'ROOM_AT_CAPACITY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  FILE_VIRUS_DETECTED: 'FILE_VIRUS_DETECTED',
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

export const FILE = {
  MAX_SIZE: 10 * 1024 * 1024,
  ALLOWED_TYPES: ['application/pdf', 'image/jpeg', 'image/png'],
} as const;
